export enum Absnotes {
  C1,
  Db1,
  D1,
  Eb1,
  E1,
  F1,
  Gb1,
  G1,
  Ab1,
  A1,
  Bb1,
  B1,
  C2,
  Db2,
  D2,
  Eb2,
  E2,
  F2,
  Gb2,
  G2,
  Ab2,
  A2,
  Bb2,
  B2,
  C3,
  Db3,
  D3,
  Eb3,
  E3,
  F3,
  Gb3,
  G3,
  Ab3,
  A3,
  Bb3,
  B3,
  C4,
  Db4,
  D4,
  Eb4,
  E4,
  F4,
  Gb4,
  G4,
  Ab4,
  A4,
  Bb4,
  B4,
  C5,
  Db5,
  D5,
  Eb5,
  E5,
  F5,
  Gb5,
  G5,
  Ab5,
  A5,
  Bb5,
  B5,
  C6,
  Db6,
  D6,
  Eb6,
  E6,
  F6,
  Gb6,
  G6,
  Ab6,
  A6,
  Bb6,
  B6,
}

const absnoteHash: { [key: string]: Absnotes } = {
  C1: Absnotes.C1,
  Db1: Absnotes.Db1,
  D1: Absnotes.D1,
  Eb1: Absnotes.Eb1,
  E1: Absnotes.E1,
  F1: Absnotes.F1,
  Gb1: Absnotes.Gb1,
  G1: Absnotes.G1,
  Ab1: Absnotes.Ab1,
  A1: Absnotes.A1,
  Bb1: Absnotes.Bb1,
  B1: Absnotes.B1,
  C2: Absnotes.C2,
  Db2: Absnotes.Db2,
  D2: Absnotes.D2,
  Eb2: Absnotes.Eb2,
  E2: Absnotes.E2,
  F2: Absnotes.F2,
  Gb2: Absnotes.Gb2,
  G2: Absnotes.G2,
  Ab2: Absnotes.Ab2,
  A2: Absnotes.A2,
  Bb2: Absnotes.Bb2,
  B2: Absnotes.B2,
  C3: Absnotes.C3,
  Db3: Absnotes.Db3,
  D3: Absnotes.D3,
  Eb3: Absnotes.Eb3,
  E3: Absnotes.E3,
  F3: Absnotes.F3,
  Gb3: Absnotes.Gb3,
  G3: Absnotes.G3,
  Ab3: Absnotes.Ab3,
  A3: Absnotes.A3,
  Bb3: Absnotes.Bb3,
  B3: Absnotes.B3,
  C4: Absnotes.C4,
  Db4: Absnotes.Db4,
  D4: Absnotes.D4,
  Eb4: Absnotes.Eb4,
  E4: Absnotes.E4,
  F4: Absnotes.F4,
  Gb4: Absnotes.Gb4,
  G4: Absnotes.G4,
  Ab4: Absnotes.Ab4,
  A4: Absnotes.A4,
  Bb4: Absnotes.Bb4,
  B4: Absnotes.B4,
  C5: Absnotes.C5,
  Db5: Absnotes.Db5,
  D5: Absnotes.D5,
  Eb5: Absnotes.Eb5,
  E5: Absnotes.E5,
  F5: Absnotes.F5,
  Gb5: Absnotes.Gb5,
  G5: Absnotes.G5,
  Ab5: Absnotes.Ab5,
  A5: Absnotes.A5,
  Bb5: Absnotes.Bb5,
  B5: Absnotes.B5,
  C6: Absnotes.C6,
  Db6: Absnotes.Db6,
  D6: Absnotes.D6,
  Eb6: Absnotes.Eb6,
  E6: Absnotes.E6,
  F6: Absnotes.F6,
  Gb6: Absnotes.Gb6,
  G6: Absnotes.G6,
  Ab6: Absnotes.Ab6,
  A6: Absnotes.A6,
  Bb6: Absnotes.Bb6,
  B6: Absnotes.B6,
}

export const absnoteValues = Object.values(absnoteHash)
export const absnoteKeys = Object.keys(absnoteHash)

export function getAbsnote(key: string): {
  absnote?: Absnotes
  success: boolean
} {
  if (Object.values(Absnotes).includes(key)) {
    return { absnote: absnoteHash[key], success: true }
  }

  return { success: false }
}

export function getAbsnoteName(absnote: Absnotes): { key: string } {
  const index = absnoteValues.indexOf(absnote)
  return { key: absnoteKeys[index] }
}
